project:
  type: website
  output-dir: docs

website: 
  title: "Alice Miao"
  navbar:
    left:
      - href: index.qmd
        text: Bio
      - href: resume.pdf  
        text: CV
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true